"""The literal grid gate and its metamorphic invariants (#243, #145).

Every cell of the grid is run on this build and classified against the
recorded ``main`` baseline: UNCHANGED, BUG_FIXED, INTENDED_CHANGE (naming the
decision), PREEXISTING_BUG (naming the issue), REGRESSION or UNDECIDED. The
gate is REGRESSION = 0 and UNDECIDED = 0. The baseline is not regenerated by
a test; record it by hand with ``grid.py --commit SHA`` under a main build and
review the diff.

The invariants below do not depend on the baseline. They relate cells of the
live grid to one another (a mirrored comparison, membership as equality, a
CASE with swapped branches, a shared value in each of its spellings, a
context against the column of its type, a number in each of its spellings)
and the same expression at three stages (inline, on a lazily staged column,
on a materialized one). A cell listed in ``PREEXISTING`` is expected to
break the invariants its issue describes, and nowhere else.
"""

from __future__ import annotations

import functools
import re
from pathlib import Path

import pytest

from . import classification, grid, oracle
from .classification import BY_MAIN, RULES, STATUSES, classify, show
from .grid import POSITIONS, cell_id, comparable, literals, outcome

BASELINE = Path(__file__).parent / "expected" / "main.jsonl"
BASELINE_COMMIT = "68d6114"
HEADER, MAIN = grid.load(BASELINE)

# Cells whose outcome is a known, unfixed defect shared with main. Each one is
# pinned: the gate expects exactly these PREEXISTING_BUG cells, and the
# invariant tests expect exactly these cells to break.
PREEXISTING = {
    # DataFusion's static in-list filter hashes floats bitwise: 0.0 is not in [-0.0, 1].
    "case_i64_f64/fm0/isin2": "#245",
}

CONTEXTS = list(grid.CONTEXTS)
LITERALS = list(literals())
GRID = {ctx: [(lit, pos) for c, lit, pos in grid.cells() if c == ctx] for ctx in CONTEXTS}

# The literals the live (non-grid) tests cover: each kind, each spelling of a
# number that matters to exactness, and each temporal flavour.
REPRESENTATIVE = [
    "i0", "i1", "i2p53p1", "imax", "f0", "fm0", "f1", "f1_5", "f2p53", "fnan",
    "D1_5", "D2p53p1", "s1", "bT", "none", "dt_mid", "dt_utc", "date2024", "pd_ns",
]


@functools.lru_cache(maxsize=None)
def live(ctx):
    """This build's outcome of every cell of the context."""
    return {cell_id(ctx, lit, pos): grid.run_cell(ctx, lit, pos) for lit, pos in GRID[ctx]}


def in_policy(ctx, lit):
    """The cells the literal policy governs: a typed value next to a value it can hold or refuse.

    String and Boolean contexts and literals follow DataFusion's own
    coercion (D-h), and ``None`` is ``IS NULL`` in a comparison (#154).
    """
    return oracle.context_kind(ctx) not in ("str", "bool") and oracle.literal_kind(lit) not in ("str", "bool", "none")


_DICTIONARY = re.compile(r"dictionary<values=(.+), indices=[^,>]+, ordered=\d>")


def shape(out):
    """The type of a result, or the class and stage of an error.

    A dictionary column keeps its encoding through fill_null and coalesce
    and loses it through CASE; the policy fixes the value type, so the
    encoding is dropped here.
    """
    if "error" in out:
        return ("error", out["error"]["class"], out["error"]["stage"])
    return ("type", _DICTIONARY.sub(r"\1", out["type"]))


def values_or_error(out):
    if "error" in out:
        return shape(out)
    return ("values", oracle.outcome_values(out))


def same_values(a, b):
    if a[0] != b[0]:
        return False
    if a[0] != "values":
        return a == b
    return len(a[1]) == len(b[1]) and all(oracle.same(x, y) for x, y in zip(a[1], b[1]))


def report(offenders):
    return "\n".join(offenders)


# --- the baseline and the rules -----------------------------------------------------


def test_baseline_is_the_recorded_main_build():
    assert HEADER["commit"] == BASELINE_COMMIT
    assert set(MAIN) == {cell_id(*c) for c in grid.cells()}


def test_rules_are_well_formed():
    names = [rule.name for rule in RULES]
    assert len(names) == len(set(names))
    for rule in RULES:
        assert rule.status in STATUSES | {BY_MAIN}, rule.name
        assert rule.status not in ("REGRESSION", "UNDECIDED"), rule.name
        assert rule.ref and rule.note, rule.name
    for cell, issue in PREEXISTING.items():
        assert issue.startswith("#"), cell


def _classified(ctx):
    head = live(ctx)
    cells = [classification.cell(ctx, lit, pos, MAIN[cell_id(ctx, lit, pos)], head[cell_id(ctx, lit, pos)]) for lit, pos in GRID[ctx]]
    return [(c, classify(c)) for c in cells]


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_gate_no_regression_no_undecided(ctx):
    offenders = []
    for c, k in _classified(ctx):
        if k.status in ("REGRESSION", "UNDECIDED"):
            offenders.append(f"{c.id} [{k.status}] {k.reason}\n  head={show(c.head)}\n  main={show(c.main)}")
    assert not offenders, report(offenders)


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_gate_preexisting_bugs_are_exactly_the_pinned_cells(ctx):
    expected = {cell: issue for cell, issue in PREEXISTING.items() if cell.startswith(ctx + "/")}
    found = {}
    for c, k in _classified(ctx):
        if k.status == "PREEXISTING_BUG":
            rule = next(r for r in RULES if r.name == k.rule)
            found[c.id] = rule.ref
    assert found == expected


def test_every_rule_classifies_a_cell():
    used = set()
    for ctx in CONTEXTS:
        used.update(k.rule for _, k in _classified(ctx) if k.rule)
    unused = [rule.name for rule in RULES if rule.name not in used]
    assert not unused, f"rules that classify no cell: {unused}"


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_oracle_context_type_matches_the_build(ctx):
    column = grid.table().derive(v=grid.context(ctx)).to_arrow().column("v")
    assert str(column.type) == oracle.CONTEXT_TYPE[ctx]


# --- invariants between cells of the live grid ---------------------------------------


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_comparison_mirror(ctx):
    """``L < x`` is ``x > L``, in every context and for every literal."""
    head = live(ctx)
    offenders = [
        f"{ctx}/{lit}: gt={show(head[cell_id(ctx, lit, 'gt')])} lt_mirror={show(head[cell_id(ctx, lit, 'lt_mirror')])}"
        for lit in LITERALS
        if comparable(head[cell_id(ctx, lit, "gt")]) != comparable(head[cell_id(ctx, lit, "lt_mirror")])
    ]
    assert not offenders, report(offenders)


MIRRORED = [("==", "=="), ("!=", "!="), ("<", ">"), ("<=", ">="), (">", "<"), (">=", "<=")]


@pytest.mark.parametrize("lit", LITERALS)
def test_comparison_mirror_at_capture(lit):
    """Python reflects ``L op x`` to ``x op' L`` before anything reaches the kernel."""
    import operator

    ops = {"==": operator.eq, "!=": operator.ne, "<": operator.lt, "<=": operator.le, ">": operator.gt, ">=": operator.ge}
    value = literals()[lit]
    t = grid.table()
    for left, right in MIRRORED:
        mirrored = t._capture_expr(lambda r: ops[left](value, r.i64))
        direct = t._capture_expr(lambda r: ops[right](r.i64, value))
        assert mirrored == direct, (lit, left, right)


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_membership_of_one_is_equality(ctx):
    """``x.is_in([L])`` is ``x == L`` wherever the policy governs the literal."""
    head = live(ctx)
    offenders = []
    for lit in LITERALS:
        if not in_policy(ctx, lit):
            continue
        isin, eq = head[cell_id(ctx, lit, "isin")], head[cell_id(ctx, lit, "eq")]
        if comparable(isin) != comparable(eq):
            offenders.append(f"{ctx}/{lit}: isin={show(isin)} eq={show(eq)}")
    assert not offenders, report(offenders)


def kleene_or(a, b):
    if a is True or b is True:
        return True
    if a is None or b is None:
        return None
    return False


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_membership_of_two_is_disjunction(ctx):
    """``x.is_in([L, 1])`` is ``(x == L) | (x == 1)``, errors included, except the pinned cells."""
    head = live(ctx)
    one = head[cell_id(ctx, "i1", "eq")]
    broken, intact = [], []
    for lit in LITERALS:
        if not in_policy(ctx, lit):
            continue
        cell = cell_id(ctx, lit, "isin2")
        isin2, eq = head[cell], head[cell_id(ctx, lit, "eq")]
        if "error" in eq:
            expected = comparable(eq)
        elif "error" in one:
            expected = comparable(one)
        else:
            expected = {"type": "bool", "values": [kleene_or(a, b) for a, b in zip(eq["values"], one["values"])]}
        holds = comparable(isin2) == expected
        if cell in PREEXISTING:
            if holds:
                intact.append(cell)
        elif not holds:
            broken.append(f"{cell}: isin2={show(isin2)} expected={expected}")
    assert not broken, report(broken)
    assert not intact, f"pinned cells that no longer break the invariant: {intact}"


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_case_branch_symmetry(ctx):
    """A CASE with the literal in the THEN branch equals one with it in the ELSE branch."""
    head = live(ctx)
    offenders = [
        f"{ctx}/{lit}: ifelse_t={show(head[cell_id(ctx, lit, 'ifelse_t')])} ifelse_f={show(head[cell_id(ctx, lit, 'ifelse_f')])}"
        for lit in LITERALS
        if comparable(head[cell_id(ctx, lit, "ifelse_t")]) != comparable(head[cell_id(ctx, lit, "ifelse_f")])
    ]
    assert not offenders, report(offenders)


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_shared_value_positions_agree(ctx):
    """fill_null, coalesce (either order) and if_else give one type, or one error, per literal."""
    head = live(ctx)
    offenders = []
    for lit in LITERALS:
        if not in_policy(ctx, lit):
            continue
        shapes = {pos: shape(head[cell_id(ctx, lit, pos)]) for pos in grid.VALUE_POSITIONS}
        if len(set(shapes.values())) > 1:
            offenders.append(f"{ctx}/{lit}: {shapes}")
    assert not offenders, report(offenders)


# A CASE context reads as the column of its unified type, and a dictionary
# column as its value type.
TWINS = {
    "case_i64_f64": "f64",
    "case_f64_i64": "f64",
    "case_d5_d38": "d38",
    "case_us_ns": "ts_ns",
    "case_i32_i64": "i64",
    "case_date_ts": "ts_ns",
}


@pytest.mark.parametrize("ctx", sorted(TWINS))
def test_case_context_reads_as_its_unified_type(ctx):
    twin = TWINS[ctx]
    head, other = live(ctx), live(twin)
    offenders = []
    for lit, pos in GRID[ctx]:
        a, b = head[cell_id(ctx, lit, pos)], other[cell_id(twin, lit, pos)]
        if shape(a) != shape(b):
            offenders.append(f"{ctx}/{lit}/{pos}: {show(a)} | {twin}: {show(b)}")
    assert not offenders, report(offenders)


def test_dictionary_context_reads_as_its_values():
    head, other = live("dict_i64"), live("i64")
    offenders = []
    for lit, pos in GRID["dict_i64"]:
        if not in_policy("i64", lit):
            continue
        a, b = head[cell_id("dict_i64", lit, pos)], other[cell_id("i64", lit, pos)]
        if not same_values(values_or_error(a), values_or_error(b)):
            offenders.append(f"dict_i64/{lit}/{pos}: {show(a)} | i64: {show(b)}")
    assert not offenders, report(offenders)


# Spellings of one number. In an integer or decimal context a comparison
# reads the number, so its outcome is the same in every spelling. In a float
# context DataFusion's own coercion stands (D-j): an int next to Float32
# compares at Float32, so 16777217 rounds to 16777216.0 there while
# 16777217.0 compares at Float64, and spellings agree only where the context
# holds the number. A shared value reads the number too, but the type
# DataFusion proposes depends on the spelling, so values compare by exact
# value where the context holds the number.
NUMBER_GROUPS = [
    ("i0", "f0", "fm0"),
    ("i1", "f1"),
    ("i2p53", "f2p53"),
    ("i2p24", "f2p24"),
    ("i2p24p1", "f2p24p1"),
    ("D1_5", "f1_5"),
    ("D2p53p1", "i2p53p1"),
]


@pytest.mark.parametrize("ctx", [c for c in CONTEXTS if oracle.context_kind(c) not in ("str", "bool")])
def test_number_parity_across_spellings(ctx):
    head = live(ctx)
    ctx_type = oracle.CONTEXT_TYPE[ctx]
    exact_context = oracle.context_kind(ctx) in oracle.EXACT_NUMERIC
    broken, intact = [], []
    for group in NUMBER_GROUPS:
        held = oracle.holds(ctx_type, oracle.literal_exact(group[0]))
        for pos in grid.COMPARISON_POSITIONS + grid.VALUE_POSITIONS:
            if not held and (pos in grid.VALUE_POSITIONS or not exact_context):
                continue
            outcomes = {lit: head[cell_id(ctx, lit, pos)] for lit in group}
            first = group[0]
            for lit in group[1:]:
                cell = cell_id(ctx, lit, pos)
                if pos in grid.COMPARISON_POSITIONS:
                    holds = comparable(outcomes[lit]) == comparable(outcomes[first])
                else:
                    holds = same_values(values_or_error(outcomes[lit]), values_or_error(outcomes[first]))
                if cell in PREEXISTING:
                    if holds:
                        intact.append(cell)
                elif not holds:
                    broken.append(f"{cell}: {show(outcomes[lit])} | {first}: {show(outcomes[first])}")
    assert not broken, report(broken)
    assert not intact, f"pinned cells that no longer break the invariant: {intact}"


TEMPORAL_LITERAL_KINDS = {"date", "dt_naive", "dt_aware"}


@pytest.mark.parametrize("ctx", sorted(grid.TEMPORAL_CONTEXTS))
def test_number_next_to_temporal_is_refused_in_every_position(ctx):
    """D-l: the refusal does not depend on where the literal meets the column."""
    head = live(ctx)
    offenders = []
    for lit in LITERALS:
        if oracle.literal_kind(lit) in TEMPORAL_LITERAL_KINDS | {"str", "none"}:
            continue
        for lit_, pos in GRID[ctx]:
            if lit_ != lit:
                continue
            out = head[cell_id(ctx, lit, pos)]
            if shape(out) != ("error", "ValueError", "plan"):
                offenders.append(f"{ctx}/{lit}/{pos}: {show(out)}")
    assert not offenders, report(offenders)


# --- the same expression at three stages ---------------------------------------------


def _staged(ctx):
    return grid.table().derive(c=grid.context(ctx))


@functools.lru_cache(maxsize=None)
def _materialized(ctx):
    from ltseq import LTSeq

    return LTSeq.from_arrow(_staged(ctx).to_arrow()).sort("k")


STAGED_CONTEXTS = ["dict_i64"] + list(grid.CASES)


@pytest.mark.parametrize("ctx", STAGED_CONTEXTS)
def test_staging_parity(ctx):
    """A context inline, as a lazily derived column and as a materialized column read alike."""
    head = live(ctx)
    staged, materialized = _staged(ctx), _materialized(ctx)
    broken, intact = [], []
    for lit, pos in GRID[ctx]:
        if lit not in REPRESENTATIVE:
            continue
        cell = cell_id(ctx, lit, pos)
        expr = grid.expression_on(lambda r: r.c, lit, pos)
        inline = comparable(head[cell])
        lazy = comparable(outcome(lambda: staged.derive(v=expr)))
        collected = comparable(outcome(lambda: materialized.derive(v=expr)))
        holds = inline == lazy == collected
        if cell in PREEXISTING:
            if holds:
                intact.append(cell)
        elif not holds:
            broken.append(f"{cell}: inline={inline} lazy={lazy} materialized={collected}")
    assert not broken, report(broken)
    assert not intact, f"pinned cells that no longer break the invariant: {intact}"


@pytest.mark.parametrize("ctx", CONTEXTS)
def test_nary_composition(ctx):
    """A third coalesce argument or a second fill_null of the same literal changes nothing."""
    from ltseq import coalesce

    head = live(ctx)
    c = grid.context(ctx)
    t = grid.table()
    offenders = []
    for lit in REPRESENTATIVE:
        if not in_policy(ctx, lit):
            continue
        value = literals()[lit]
        coal3 = outcome(lambda: t.derive(v=lambda r: coalesce(c(r), value, value)))
        fill2 = outcome(lambda: t.derive(v=lambda r: c(r).fill_null(value).fill_null(value)))
        for pos, out in (("coal", coal3), ("fill", fill2)):
            if comparable(out) != comparable(head[cell_id(ctx, lit, pos)]):
                offenders.append(f"{ctx}/{lit}/{pos}: n-ary={show(out)} binary={show(head[cell_id(ctx, lit, pos)])}")
    assert not offenders, report(offenders)
