from typing import TYPE_CHECKING
from .base import Expr

if TYPE_CHECKING:
    from .types import CallExpr


class StringAccessor:
    def __init__(self, expr: Expr) -> None: ...
    def contains(self, pattern: str) -> CallExpr: ...
    def starts_with(self, prefix: str) -> CallExpr: ...
    def ends_with(self, suffix: str) -> CallExpr: ...
    def lower(self) -> CallExpr: ...
    def upper(self) -> CallExpr: ...
    def strip(self) -> CallExpr: ...
    def lstrip(self) -> CallExpr: ...
    def rstrip(self) -> CallExpr: ...
    def len(self) -> CallExpr: ...
    def slice(self, start: int, length: int) -> CallExpr: ...
    def left(self, n: int) -> CallExpr: ...
    def right(self, n: int) -> CallExpr: ...
    def replace(self, old: str, new: str) -> CallExpr: ...
    def concat(self, *others: str | Expr) -> CallExpr: ...
    def split(self, delimiter: str, index: int) -> CallExpr: ...
    def like(self, pattern: str) -> CallExpr: ...
    def regex_match(self, pattern: str) -> CallExpr: ...
    def pad_left(self, width: int, char: str = ...) -> CallExpr: ...
    def pad_right(self, width: int, char: str = ...) -> CallExpr: ...
    def pos(self, sub: str) -> CallExpr: ...
    def isalpha(self) -> CallExpr: ...
    def isdigit(self) -> CallExpr: ...
    def islower(self) -> CallExpr: ...
    def isupper(self) -> CallExpr: ...
    def asc(self) -> CallExpr: ...


class TemporalAccessor:
    def __init__(self, expr: Expr) -> None: ...
    def year(self) -> CallExpr: ...
    def month(self) -> CallExpr: ...
    def day(self) -> CallExpr: ...
    def hour(self) -> CallExpr: ...
    def minute(self) -> CallExpr: ...
    def second(self) -> CallExpr: ...
    def millisecond(self) -> CallExpr: ...
    def weekday(self) -> CallExpr: ...
    def age(self) -> CallExpr: ...
    def add(
        self,
        days: int = ...,
        months: int = ...,
        years: int = ...,
        hours: int = ...,
        minutes: int = ...,
        seconds: int = ...,
        weeks: int = ...,
    ) -> CallExpr: ...
    def diff(self, other: Expr, unit: str = ...) -> CallExpr: ...
