from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .core_types import BinOpExpr, LiteralExpr, UnaryOpExpr
    from .types import CallExpr, LookupExpr


class Expr:
    @staticmethod
    def _coerce(value: Any) -> Expr: ...
    def serialize(self) -> dict[str, Any]: ...

    # Arithmetic
    def __add__(self, other: Expr | Any) -> BinOpExpr: ...
    def __sub__(self, other: Expr | Any) -> BinOpExpr: ...
    def __mul__(self, other: Expr | Any) -> BinOpExpr: ...
    def __truediv__(self, other: Expr | Any) -> BinOpExpr: ...
    def __floordiv__(self, other: Expr | Any) -> BinOpExpr: ...
    def __mod__(self, other: Expr | Any) -> BinOpExpr: ...

    # Comparison
    def __eq__(self, other: Expr | Any) -> BinOpExpr: ...  # type: ignore[override]
    def __ne__(self, other: Expr | Any) -> BinOpExpr: ...  # type: ignore[override]
    def __lt__(self, other: Expr | Any) -> BinOpExpr: ...
    def __le__(self, other: Expr | Any) -> BinOpExpr: ...
    def __gt__(self, other: Expr | Any) -> BinOpExpr: ...
    def __ge__(self, other: Expr | Any) -> BinOpExpr: ...

    # Logical
    def __and__(self, other: Expr | Any) -> BinOpExpr: ...
    def __or__(self, other: Expr | Any) -> BinOpExpr: ...
    def __invert__(self) -> UnaryOpExpr: ...
    def __abs__(self) -> CallExpr: ...

    # Right-hand
    def __radd__(self, other: Any) -> BinOpExpr: ...
    def __rsub__(self, other: Any) -> BinOpExpr: ...
    def __rmul__(self, other: Any) -> BinOpExpr: ...
    def __rtruediv__(self, other: Any) -> BinOpExpr: ...
    def __rfloordiv__(self, other: Any) -> BinOpExpr: ...
    def __rmod__(self, other: Any) -> BinOpExpr: ...

    # Utility methods
    def fill_null(self, default: Any) -> CallExpr: ...
    def is_null(self) -> CallExpr: ...
    def is_not_null(self) -> CallExpr: ...
    def is_in(self, values: list[Any]) -> CallExpr: ...
    def between(self, low: Any, high: Any) -> BinOpExpr: ...
    def cast(self, dtype: str) -> CallExpr: ...
    def abs(self) -> CallExpr: ...
    def round(self, decimals: int = ...) -> CallExpr: ...
    def floor(self) -> CallExpr: ...
    def ceil(self) -> CallExpr: ...
    def pct_change(self) -> BinOpExpr: ...
    def lookup(self, target_table: Any, column: str, join_key: str | None = ...) -> LookupExpr: ...


# Conditional / null
def if_else(condition: Expr, true_value: Any, false_value: Any) -> CallExpr: ...
def coalesce(*args: Expr | Any) -> CallExpr: ...
def nvl(x: Expr, default: Expr | Any) -> CallExpr: ...
def ifa(cond: Expr, value: Expr | Any) -> CallExpr: ...

# Aggregate conditionals
def count_if(predicate: Expr) -> CallExpr: ...
def sum_if(predicate: Expr, column: Expr) -> CallExpr: ...
def avg_if(predicate: Expr, column: Expr) -> CallExpr: ...
def min_if(predicate: Expr, column: Expr) -> CallExpr: ...
def max_if(predicate: Expr, column: Expr) -> CallExpr: ...

# Ranking / window
def row_number() -> CallExpr: ...
def rank() -> CallExpr: ...
def dense_rank() -> CallExpr: ...
def ntile(n: int) -> CallExpr: ...

# Math
def sqrt(x: Expr) -> CallExpr: ...
def power(x: Expr, n: Expr | float | int) -> CallExpr: ...
def sign(x: Expr) -> CallExpr: ...
def log(x: Expr, base: float | int | None = ...) -> CallExpr: ...
def ln(x: Expr) -> CallExpr: ...
def exp(x: Expr) -> CallExpr: ...
def sin(x: Expr) -> CallExpr: ...
def cos(x: Expr) -> CallExpr: ...
def tan(x: Expr) -> CallExpr: ...
def asin(x: Expr) -> CallExpr: ...
def acos(x: Expr) -> CallExpr: ...
def atan(x: Expr) -> CallExpr: ...
def atan2(y: Expr, x: Expr) -> CallExpr: ...
def rand() -> CallExpr: ...
def gcd(a: Expr, b: Expr) -> CallExpr: ...
def lcm(a: Expr, b: Expr) -> CallExpr: ...
def factorial(n: Expr) -> CallExpr: ...

# String globals
def str_char(n: Expr) -> CallExpr: ...
def concat_ws(delimiter: str, *cols: Expr) -> CallExpr: ...

# Datetime globals
def now() -> CallExpr: ...
def today() -> CallExpr: ...

# Aggregate expressions
def skew(col: Expr) -> CallExpr: ...
def corr(col_a: Expr, col_b: Expr) -> CallExpr: ...
def covar(col_a: Expr, col_b: Expr) -> CallExpr: ...
def concat_agg(col: Expr, delimiter: str = ...) -> CallExpr: ...
