from .types import ColumnExpr, CallExpr


class _SchemaAttr(ColumnExpr):
    def __getattr__(self, name: str) -> ColumnExpr: ...


class SchemaProxy:
    def __init__(self, schema: dict[str, str]) -> None: ...
    def __getattr__(self, name: str) -> _SchemaAttr: ...
    def get_schema(self) -> dict[str, str]: ...


class NestedSchemaProxy:
    def __init__(self, alias: str, prefixed_columns: dict[str, str]) -> None: ...
    def __getattr__(self, name: str) -> ColumnExpr: ...
