from typing import Any, Callable
from .base import Expr
from .accessors import StringAccessor, TemporalAccessor
from .core_types import BinOpExpr, LiteralExpr, UnaryOpExpr
from .lookup_expr import LookupExpr


class ColumnExpr(Expr):
    name: str
    def __init__(self, name: str) -> None: ...
    def serialize(self) -> dict[str, Any]: ...

    @property
    def s(self) -> StringAccessor: ...
    @property
    def dt(self) -> TemporalAccessor: ...

    # Common window / sequence methods
    def shift(self, n: int = ..., default: Any = ...) -> CallExpr: ...
    def rolling(self, window: int) -> CallExpr: ...
    def diff(self, n: int = ...) -> CallExpr: ...

    # Aggregation methods (used inside agg() lambdas)
    def sum(self) -> CallExpr: ...
    def mean(self) -> CallExpr: ...
    def min(self) -> CallExpr: ...
    def max(self) -> CallExpr: ...
    def count(self) -> CallExpr: ...
    def std(self) -> CallExpr: ...
    def var(self) -> CallExpr: ...
    def first(self) -> CallExpr: ...
    def last(self) -> CallExpr: ...
    def median(self) -> CallExpr: ...

    # Fallback for any other method call (e.g. r.col.custom_func())
    def __getattr__(self, name: str) -> Any: ...


class CallExpr(Expr):
    func: str
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    on: Any | None

    def __init__(
        self,
        func: str,
        args: tuple[Any, ...] = ...,
        kwargs: dict[str, Any] | None = ...,
        on: Any | None = ...,
    ) -> None: ...
    def serialize(self) -> dict[str, Any]: ...

    @property
    def s(self) -> StringAccessor: ...
    @property
    def dt(self) -> TemporalAccessor: ...

    # Rolling chain targets (e.g. r.col.rolling(3).mean())
    def mean(self) -> CallExpr: ...
    def shift(self, n: int = ..., default: Any = ...) -> CallExpr: ...
    def sum(self) -> CallExpr: ...
    def std(self) -> CallExpr: ...
    def min(self) -> CallExpr: ...
    def max(self) -> CallExpr: ...
    def count(self) -> CallExpr: ...
    def var(self) -> CallExpr: ...
    def median(self) -> CallExpr: ...
    def first(self) -> CallExpr: ...
    def last(self) -> CallExpr: ...

    def over(
        self,
        partition_by: Any | None = ...,
        order_by: Any | None = ...,
        descending: bool = ...,
    ) -> WindowExpr: ...

    def __getattr__(self, name: str) -> Any: ...


class WindowExpr(Expr):
    expr: Any
    partition_by: Any | None
    order_by: Any | None
    descending: bool

    def __init__(
        self,
        expr: Any,
        partition_by: Any | None = ...,
        order_by: Any | None = ...,
        descending: bool = ...,
    ) -> None: ...
    def serialize(self) -> dict[str, Any]: ...


__all__ = [
    "ColumnExpr",
    "CallExpr",
    "WindowExpr",
    "LiteralExpr",
    "BinOpExpr",
    "UnaryOpExpr",
    "LookupExpr",
    "StringAccessor",
    "TemporalAccessor",
]
