from typing import TYPE_CHECKING, Callable

if TYPE_CHECKING:
    from .core import LTSeq
    from .grouping.nested_table import NestedTable


class GroupBy:
    def __init__(self, table: LTSeq, key: str | Callable) -> None: ...
    def agg(self, **aggregations: Callable) -> LTSeq: ...


class AggregationMixin:
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def cum_sum(self, *cols: str | Callable) -> LTSeq: ...
    def group_ordered(self, grouping_fn: Callable) -> NestedTable: ...
    def group_consecutive(self, grouping_fn: Callable) -> NestedTable: ...
    def group_sorted(self, key: Callable) -> NestedTable: ...
    def agg(self, by: Callable | None = ..., **aggregations: Callable) -> LTSeq: ...
    def group_by(self, key: str | Callable) -> GroupBy: ...
