from typing import Any


class Cursor:
    def __init__(self, rust_cursor: Any) -> None: ...
    def __iter__(self) -> Cursor: ...
    def __next__(self) -> Any: ...  # returns pyarrow.RecordBatch

    @property
    def schema(self) -> dict[str, str]: ...
    @property
    def columns(self) -> list[str]: ...
    @property
    def source(self) -> str: ...
    @property
    def exhausted(self) -> bool: ...

    def to_pandas(self) -> Any: ...   # returns pandas.DataFrame
    def to_arrow(self) -> Any: ...    # returns pyarrow.Table
    def count(self) -> int: ...
