class LTSeqError(Exception): ...
class SortRequiredError(LTSeqError, ValueError): ...
class SchemaMismatchError(LTSeqError, ValueError): ...
class ColumnNotFoundError(LTSeqError, ValueError, AttributeError): ...
