from typing import TYPE_CHECKING, Callable

if TYPE_CHECKING:
    from .core import LTSeq


class LinkedTable:
    _schema: dict[str, str]
    def __init__(
        self,
        source_table: LTSeq,
        target_table: LTSeq,
        join_fn: Callable,
        alias: str,
        join_type: str = ...,
    ) -> None: ...
    def __len__(self) -> int: ...
    def show(self, n: int = ...) -> None: ...
    def filter(self, predicate: Callable) -> LinkedTable | LTSeq: ...
    def select(self, *cols: str | Callable) -> LTSeq: ...
    def derive(self, mapper: Callable) -> LinkedTable: ...
    def sort(self, *key_exprs: str | Callable) -> LinkedTable: ...
    def slice(self, start: int, end: int) -> LinkedTable: ...
    def distinct(self, key_fn: Callable | None = ...) -> LinkedTable: ...
    def link(
        self,
        target_table: LTSeq,
        on: Callable,
        as_: str,
        join_type: str = ...,
    ) -> LinkedTable: ...
