from typing import TYPE_CHECKING, Callable, Literal

if TYPE_CHECKING:
    from .core import LTSeq

JoinHow = Literal["inner", "left", "right", "full"]


class LinkedTable:
    _schema: dict[str, str]
    _join_type: str
    _source: LTSeq
    _target: LTSeq
    _alias: str
    def __init__(
        self,
        source_table: LTSeq,
        target_table: LTSeq,
        join_fn: Callable,
        alias: str,
        join_type: JoinHow = ...,
    ) -> None: ...
    def _ensure_join_plan(self) -> LTSeq: ...
    def to_ltseq(self) -> LTSeq: ...
    def collect(self) -> LTSeq: ...
    def __len__(self) -> int: ...
    def show(self, n: int = ...) -> None: ...
    def filter(self, predicate: Callable) -> LTSeq: ...
    def select(self, *cols: str | Callable) -> LTSeq: ...
    def derive(self, *args: Callable, **kwargs: Callable) -> LTSeq: ...
    def sort(self, *key_exprs: str | Callable, **kwargs: object) -> LTSeq: ...
    def slice(self, offset: int, length: int) -> LTSeq: ...
    def distinct(self, key_fn: Callable | None = ...) -> LTSeq: ...
    def link(
        self,
        target_table: LTSeq,
        on: Callable,
        as_: str,
        join_type: JoinHow = ...,
    ) -> LinkedTable: ...
