from typing import Any


class LTSeqCursor:
    def next_batch(self) -> bytes | None: ...
    def get_schema(self) -> list[tuple[str, str]]: ...
    def get_column_names(self) -> list[str]: ...
    def get_source(self) -> str: ...
    def is_exhausted(self) -> bool: ...


class LTSeqTable:
    @classmethod
    def from_csv(cls, path: str, has_header: bool = ...) -> LTSeqTable: ...
    @classmethod
    def from_parquet(cls, path: str) -> LTSeqTable: ...
    @classmethod
    def scan_csv(cls, path: str, has_header: bool = ...) -> LTSeqCursor: ...
    @classmethod
    def scan_parquet(cls, path: str) -> LTSeqCursor: ...
    @classmethod
    def load_arrow_ipc(cls, ipc_buffers: list[bytes]) -> LTSeqTable: ...

    def __init__(self) -> None: ...
    def get_schema_dict(self) -> dict[str, str]: ...
    def show(self, n: int = ...) -> str: ...
    def count(self) -> int: ...
    def to_arrow_ipc(self) -> list[bytes]: ...
    def filter(self, expr_dict: dict[str, Any]) -> LTSeqTable: ...
    def select(self, exprs: list[dict[str, Any]]) -> LTSeqTable: ...
    def derive(self, derived_cols: dict[str, dict[str, Any]]) -> LTSeqTable: ...
    def rename_columns(self, mapping: dict[str, str]) -> LTSeqTable: ...
    def drop_columns(self, cols: list[str]) -> LTSeqTable: ...
    def sort_by(self, key_exprs: list[dict[str, Any]], descending: list[bool]) -> LTSeqTable: ...
    def distinct(self, key_exprs: list[dict[str, Any]] | None = ...) -> LTSeqTable: ...
    def slice(self, offset: int = ..., length: int | None = ...) -> LTSeqTable: ...
    def cum_sum(self, exprs: list[dict[str, Any]]) -> LTSeqTable: ...
    def join(self, other: LTSeqTable, left_key_expr: Any, right_key_expr: Any, how: str, suffix: str) -> LTSeqTable: ...
    def asof_join(self, other: LTSeqTable, left_key: str, right_key: str, direction: str = ...) -> LTSeqTable: ...
    def semi_join(self, other: LTSeqTable, left_key_expr: Any, right_key_expr: Any) -> LTSeqTable: ...
    def anti_join(self, other: LTSeqTable, left_key_expr: Any, right_key_expr: Any) -> LTSeqTable: ...
    def agg(self, grouping_expr: dict[str, Any] | None, agg_exprs: dict[str, dict[str, Any]]) -> LTSeqTable: ...
    def union(self, other: LTSeqTable) -> LTSeqTable: ...
    def intersect(self, other: LTSeqTable, on_expr: dict[str, Any] | None = ...) -> LTSeqTable: ...
    def diff(self, other: LTSeqTable, on_expr: dict[str, Any] | None = ...) -> LTSeqTable: ...
    def rvs(self) -> LTSeqTable: ...
    def step(self, n: int) -> LTSeqTable: ...
    def align(self, ref_sequence: list[Any], key_col: str) -> LTSeqTable: ...
    def search_first(self, expr_dict: dict[str, Any]) -> LTSeqTable: ...
    def search_pattern(self, step_exprs: list[dict[str, Any]], partition_by: str | None = ...) -> LTSeqTable: ...
    def search_pattern_count(self, step_exprs: list[dict[str, Any]], partition_by: str | None = ...) -> int: ...
    def pivot(self, index_cols: list[str], columns: str, values: str, agg_fn: str) -> LTSeqTable: ...
    def is_subset(self, other: LTSeqTable, on_expr: dict[str, Any] | None = ...) -> bool: ...
    def insert_row(self, pos: int, row_dict: dict[str, Any]) -> LTSeqTable: ...
    def delete_rows(self, pos: int) -> LTSeqTable: ...
    def conditional_update(self, expr_dict: dict[str, Any], updates: dict[str, Any]) -> LTSeqTable: ...
    def modify_row(self, pos: int, updates: dict[str, Any]) -> LTSeqTable: ...
    def write_csv(self, path: str) -> None: ...
    def write_parquet(self, path: str, compression: str | None = ...) -> None: ...
    def filter_where(self, where_clause: str) -> LTSeqTable: ...
    def first_row(self) -> LTSeqTable: ...
    def last_row(self) -> LTSeqTable: ...
    def derive_window_sql(self, derive_exprs: dict[str, str]) -> LTSeqTable: ...
    def group_ordered_count(self, expr_dict: dict[str, Any]) -> int: ...
