from typing import TYPE_CHECKING, Any, Callable, Iterator

if TYPE_CHECKING:
    from .core import LTSeq


class SQLPartitionedTable:
    def __getitem__(self, key: Any) -> LTSeq: ...
    def __iter__(self) -> Iterator[LTSeq]: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[Any]: ...
    def values(self) -> list[LTSeq]: ...
    def items(self) -> Iterator[tuple[Any, LTSeq]]: ...
    def map(self, fn: Callable[[LTSeq], LTSeq]) -> PartitionedTable: ...
    def to_list(self) -> list[LTSeq]: ...


class PartitionedTable:
    def __getitem__(self, key: Any) -> LTSeq: ...
    def __iter__(self) -> Iterator[LTSeq]: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[Any]: ...
    def values(self) -> list[LTSeq]: ...
    def items(self) -> Iterator[tuple[Any, LTSeq]]: ...
    def map(self, fn: Callable[[LTSeq], LTSeq]) -> PartitionedTable: ...
    def to_list(self) -> list[LTSeq]: ...
