from typing import TYPE_CHECKING, Any, Callable

if TYPE_CHECKING:
    from ..core import LTSeq
    from ..expr import CallExpr


class NestedTable:
    _is_sorted: bool
    def __init__(self, ltseq_instance: LTSeq, grouping_lambda: Callable, is_sorted: bool = ...) -> None: ...
    def __len__(self) -> int: ...
    def to_pandas(self) -> Any: ...   # returns pandas.DataFrame
    def flatten(self) -> LTSeq: ...
    def first(self) -> LTSeq: ...
    def last(self) -> LTSeq: ...
    def count(self) -> CallExpr: ...
    # Lambdas receive FilterGroupProxy / DeriveGroupProxy at runtime, but the
    # proxies' annotations understate what capture supports (see issue #94),
    # so the stubs stay permissive until group expressions move to the Rust seam.
    def filter(self, group_predicate: Callable[..., Any]) -> NestedTable: ...
    def derive(self, group_mapper: Callable[..., Any]) -> LTSeq: ...
    def agg(self, group_mapper: Callable[..., Any]) -> LTSeq: ...
