from typing import TYPE_CHECKING, Any, Callable
from .proxies.group_proxy import GroupProxy

if TYPE_CHECKING:
    from ..core import LTSeq
    from ..expr import ColumnExpr


class NestedTable:
    def __len__(self) -> int: ...
    def to_pandas(self) -> Any: ...   # returns pandas.DataFrame
    def flatten(self) -> LTSeq: ...
    def first(self) -> LTSeq: ...
    def last(self) -> LTSeq: ...
    def count(self) -> ColumnExpr: ...
    def filter(self, group_predicate: Callable[[GroupProxy], bool]) -> NestedTable: ...
    def derive(self, group_mapper: Callable[[GroupProxy], dict[str, Any]]) -> LTSeq: ...
