from typing import Callable
from .row_proxy import RowProxy


class GroupProxy:
    # Basic group info
    def count(self) -> int: ...
    def first(self) -> RowProxy: ...
    def last(self) -> RowProxy: ...

    # Aggregations (column name required)
    def max(self, column_name: str | None = ...) -> object: ...
    def min(self, column_name: str | None = ...) -> object: ...
    def sum(self, column_name: str | None = ...) -> object: ...
    def avg(self, column_name: str | None = ...) -> object: ...
    def mean(self, column_name: str | None = ...) -> object: ...
    def std(self, column_name: str | None = ...) -> object: ...
    def stddev(self, column_name: str | None = ...) -> object: ...
    def variance(self, column_name: str | None = ...) -> object: ...
    def var(self, column_name: str | None = ...) -> object: ...
    def median(self, column_name: str | None = ...) -> object: ...
    def percentile(self, column_name: str, p: float) -> object: ...
    def mode(self, column_name: str | None = ...) -> object: ...
    def skew(self, column_name: str | None = ...) -> object: ...
    def corr(self, col_a: str, col_b: str) -> object: ...
    def covar(self, col_a: str, col_b: str) -> object: ...
    def concat_agg(self, column_name: str, delimiter: str = ...) -> str: ...
    def top_k(self, column_name: str, k: int) -> list[object]: ...

    # Conditional aggregations
    def count_if(self, predicate: Callable[[RowProxy], bool]) -> int: ...
    def sum_if(self, predicate: Callable[[RowProxy], bool], column_name: str) -> object: ...
    def avg_if(self, predicate: Callable[[RowProxy], bool], column_name: str) -> object: ...
    def min_if(self, predicate: Callable[[RowProxy], bool], column_name: str) -> object: ...
    def max_if(self, predicate: Callable[[RowProxy], bool], column_name: str) -> object: ...

    # Quantifiers
    def all(self, predicate: Callable[[RowProxy], bool]) -> bool: ...
    def any(self, predicate: Callable[[RowProxy], bool]) -> bool: ...
    def none(self, predicate: Callable[[RowProxy], bool]) -> bool: ...
